resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    clean: true
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      deploymentScope: 'Subscription'
      azureResourceManagerConnection: '$(azureResourceManagerConnection)'
      subscriptionId: '$(subscriptionId)'
      location: 'Australia East'
      templateLocation: 'Linked artifact'
      csmFile: 'azuredeploy.json'
      csmParametersFile: 'azuredeploy.parameters.json'
      deploymentMode: 'Incremental'
